apiVersion: v1
appVersion: 5.0.1
description: Schema Registry provides a serving layer for your metadata. It provides
  a RESTful interface for storing and retrieving Avro schemas. It stores a versioned
  history of all schemas, provides multiple compatibility settings and allows evolution
  of schemas according to the configured compatibility setting. It provides serializers
  that plug into Kafka clients that handle schema storage and retrieval for Kafka
  messages that are sent in the Avro format.
home: https://docs.confluent.io/current/schema-registry/docs/index.html
icon: https://www.confluent.io/wp-content/themes/confluent/assets/images/confluent-logo-300.png
keywords:
- confluent
- kafka
- schema-registry
maintainers:
- email: ben@spothero.com
  name: benjigoldberg
name: t8-schema-registry
sources:
- https://github.com/confluentinc/schema-registry
- https://github.com/confluentinc/cp-docker-images
version: 1.1.3
